### ISSUE TITLE
이벤트 만들기 측면 살짝 짤리는 이슈

### ISSUE THREAD

**Issue by JeonK1** [mash-up-kr/gabbangzip-Android#232]
## Overview (Required)
- 이벤트 만들기 측면 살짝 짤리는 이슈

### 버그내용
- 이벤트 만들기 측면 살짝 짤리는 이슈

### ScreenShots
![image](https://github.com/user-attachments/assets/4940972e-7c56-4588-bf6d-f062df60003a)

![image](https://github.com/user-attachments/assets/8f010afd-1a26-404c-a119-9d8b0c36c263)

**Comment by sooziini** [comment]
ㅋㅋㅋㅋ아 전체 패딩줬나봐 나
