### ISSUE TITLE
그룹 상세 네컷사진 간헐적으로 노출 안되는 이슈

### ISSUE THREAD

**Issue by JeonK1** [mash-up-kr/gabbangzip-Android#250]
## Overview (Required)
- 그룹 상세 네컷사진 간헐적으로 노출 안되는 이슈

### 버그내용
- 그룹 상세 네컷사진 간헐적으로 노출 되지 않음

### 재현경로
- 그룹상세 들어왔다가 나갔다가 반복하다보면 재현됨

## ScreenShots
Case1| Case2
:--: | :--:
<img src="https://github.com/user-attachments/assets/65bd8e68-8766-44bd-ab55-465bd6c7884e" width="300" /> | <img src="https://github.com/user-attachments/assets/4dcb2b49-76d3-47d0-b079-19f293985583" width="300" />

**Comment by oreocube** [comment]
이거 이미지 크기가 너무 커서 종종 그런거같은데 자체적으로 좀 줄여서 보내는게 나을듯 그룹상세만 그러는것도 아니라서
