### ISSUE TITLE
그룹 나가기 API

### ISSUE THREAD

**Issue by JeonK1** [mash-up-kr/gabbangzip-Android#295]
## Overview (Required)
- 그룹 나가기 API

## Links
- http://ec2-43-203-14-157.ap-northeast-2.compute.amazonaws.com/swagger-ui/index.html#/%EA%B7%B8%EB%A3%B9/withdrawGroup

**Comment by wandson88** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
