### ISSUE TITLE
CI 세팅

### ISSUE THREAD

**Issue by sooziini** [mash-up-kr/gabbangzip-Android#5]
## Overview (Required)
- Github Actions로 CI 세팅
- ktlint 적용

## Links
- https://medium.com/sungbinland/github-actions-%EC%9C%BC%EB%A1%9C-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-ci-cd-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0-1aaaa6595c4a

**Comment by sooziini** [comment]
/gabbangzip-Android/app/src/test/java/com/mashup/gabbangzip/shared_album/ExampleUnitTest.kt:1:1 Package name must not contain underscore (cannot be auto-corrected)

**Comment by JeonK1** [comment]
> /gabbangzip-Android/app/src/test/java/com/mashup/gabbangzip/shared_album/ExampleUnitTest.kt:1:1 Package name must not contain underscore (cannot be auto-corrected)

아 package 명 변경해야하네.. ㅠㅠ
@sooziini 이거 따로 issue 로 만드는게 좋을까?!

**Comment by sooziini** [comment]
@JeonK1 @SEO-J17 @oreocube 
저 부분도 ktlintCheck해서 나온 부분이니까 내가 package 명 바꿔서 같이 올릴게 .ㅎㅎ
다만 마침 물어보려했는데 말이지 지금 package 명이 shared_album으로 되어있는데 이걸 `com.mashup.gabbangzip.sharedalbum`으로 바꿔야 할지 `com.mashup.gabbangzip.sharedAlbum`으로 바꿔야 할 지 고민이야

아래 naming rules 보면 소문자 이어붙이거나 camel case 사용하라고 되어있엉 다들 어떻게 생각하는지 궁금하니까 코멘트 바람. 난 첫 번째 소문자 이어붙이기를 선호하는 편~ ^^~
https://kotlinlang.org/docs/coding-conventions.html#naming-rules

**Comment by JeonK1** [comment]
@sooziini 나도 소문자 이어붙이기 한표

**Comment by SEO-J17** [comment]
소문자로 기기.

**Comment by SEO-J17** [comment]
@JeonK1 @sooziini 근데 소문자를 선호하는 이유가 있을까~? (진짜 궁금해서) 뭔가 카멜 케이스로 하면 가시성도 좋을 것 같고 막막 그럴거 같은데 이유가 궁금한걸?

**Comment by JeonK1** [comment]
나는 그렇게 큰 이유가 있는건 아니구 패키지명 앞쪽이 mashup.gabbangzip 이런식으로 다 소문자로 되어있어서 추후 package 명 지어줄 땐 카멜로 짓더라도 app name 까지는 가독성 심각한거 아니면 모두 소문자로 하고 싶었었어!

**Comment by oreocube** [comment]
나도 소문자 좋아~ 근데 나는 별 이유는 없어 그냥 취향

**Comment by sooziini** [comment]
나도 com.mashup.gabbangzip이 다 소문자라 소문자로 맞추고 싶어서~
